scrabble_two_letter_words = {'od', 'am', 'fe', 'do', 'na', 'to', 'oh', 'es', 'ed', 'fa', 'yo', 'un', 'em', 'in', 'nu',
                             'mm', 'ar', 'oe', 'po', 'eh', 'ai', 'ok', 'ew', 'or', 'ti', 'en', 'ad', 'pe', 'aa', 'no',
                             'if', 'de', 'xi', 'al', 'be', 'si', 'te', 'ut', 'za', 'um', 'et', 'up', 'ba', 'on', 'ha',
                             'as', 'he', 'er', 'my', 'jo', 'ax', 'mu', 'ta', 'us', 're', 'ye', 'ag', 'da', 'ay', 'ne',
                             'of', 'ya', 'ae', 'an', 'ef', 'ex', 'mo', 'me', 'id', 'la', 'op', 'gi', 'is', 'om', 'at',
                             'by', 'ow', 'ab', 'ho', 'hm', 'ma', 'os', 'ka', 'bi', 'pi', 'uh', 'qi', 'ki', 'mi', 'pa',
                             'sh', 'ox', 'we', 'wo', 'ah', 'go', 'xu', 'oi', 'lo', 'aw', 'so', 'it', 'oy', 'hi', 'el',
                             'bo', 'li'}

scrabble_three_letter_words = {'wot', 'ava', 'gib', 'jin', 'sip', 'yah', 'ugh', 'biz', 'pew', 'wok', 'foe', 'nos',
                               'zep', 'alp', 'ons', 'ani', 'ilk', 'aby', 'bra', 'dex', 'elf', 'rom', 'hom', 'twa',
                               'ulu', 'vee', 'way', 'bur', 'kea', 'mow', 'zas', 'due', 'eme', 'sen', 'awa', 'dup',
                               'app', 'gae', 'moc', 'pah', 'icy', 'rat', 'car', 'aba', 'pul', 'neg', 'ode', 'dry',
                               'bad', 'lop', 'org', 'nav', 'pan', 'bug', 'oof', 'avo', 'qua', 'zuz', 'dow', 'saw',
                               'cap', 'arb', 'dib', 'nay', 'coy', 'hip', 'ole', 'san', 'wit', 'ask', 'err', 'ion',
                               'mos', 'haj', 'fen', 'tow', 'ane', 'hop', 'bah', 'lee', 'job', 'ivy', 'oca', 'jaw',
                               'poi', 'hat', 'auk', 'ped', 'nut', 'daw', 'pop', 'vet', 'tar', 'ged', 'rin', 'pit',
                               'woe', 'ben', 'yag', 'caf', 'bey', 'zit', 'lug', 'law', 'tux', 'bye', 'dap', 'mic',
                               'bit', 'hmm', 'mac', 'waw', 'tod', 'als', 'khi', 'azo', 'dor', 'fit', 'goo', 'nae',
                               'tew', 'sha', 'dom', 'sig', 'fox', 'awe', 'del', 'moo', 'nab', 'ers', 'tae', 'vug',
                               'til', 'tot', 'uke', 'lox', 'gap', 'grr', 'tun', 'eye', 'ant', 'tsk', 'vas', 'win',
                               'wad', 'wud', 'kir', 'fry', 'pus', 'mis', 'zap', 'wae', 'ore', 'wiz', 'baa', 'bog',
                               'dum', 'mop', 'vis', 'som', 'pyx', 'nth', 'ova', 'cru', 'col', 'eff', 'pee', 'try',
                               'eft', 'pax', 'log', 'sim', 'ami', 'kop', 'mem', 'pos', 'hut', 'rap', 'tam', 'ups',
                               'veg', 'hog', 'pub', 'lag', 'rod', 'dev', 'fob', 'gat', 'poo', 'dol', 'sec', 'foh',
                               'key', 'son', 'bud', 'bop', 'jot', 'lek', 'van', 'zek', 'arc', 'kue', 'oud', 'oik',
                               'sew', 'you', 'nib', 'tet', 'hup', 'cig', 'orb', 'pur', 'ill', 'feu', 'fig', 'eld',
                               'gin', 'tix', 'uni', 'gyp', 'tut', 'ice', 'bee', 'jee', 'yes', 'bin', 'sow', 'hex',
                               'sob', 'toe', 'net', 'sel', 'wye', 'cel', 'ras', 'ski', 'wry', 'sae', 'rot', 'gos',
                               'gnu', 'hyp', 'mut', 'neb', 'jeu', 'naw', 'fet', 'rev', 'vox', 'pud', 'map', 'dub',
                               'hag', 'tax', 'owe', 'haw', 'bid', 'tor', 'opt', 'red', 'yet', 'ark', 'coo', 'leg',
                               'reb', 'bes', 'teg', 'gum', 'fab', 'pep', 'dew', 'gay', 'pup', 'tab', 'koa', 'pun',
                               'koi', 'sea', 'apt', 'big', 'raw', 'urn', 'cor', 'nip', 'ahs', 'set', 'cur', 'dos',
                               'lid', 'guv', 'eon', 'lob', 'mod', 'hid', 'pho', 'end', 'oma', 'lac', 'ags', 'jib',
                               'pet', 'och', 'jut', 'rai', 'bob', 'sum', 'sou', 'fun', 'ods', 'sup', 'lex', 'par',
                               'pot', 'kor', 'pst', 'tel', 'caw', 'aal', 'yob', 'rax', 'mon', 'ray', 'roo', 'oka',
                               'gar', 'gee', 'duo', 'adz', 'eew', 'fon', 'rim', 'chi', 'bio', 'joy', 'sly', 'day',
                               'kin', 'oms', 'dif', 'tav', 'kip', 'vav', 'vig', 'sal', 'sei', 'tub', 'tap', 'rem',
                               'gob', 'sax', 'ebb', 'foy', 'nob', 'hub', 'fud', 'owl', 'uts', 'bys', 'sis', 'ads',
                               'emo', 'ham', 'reg', 'gid', 'aff', 'gem', 'wee', 'pis', 'aye', 'cot', 'ids', 'the',
                               'hot', 'yam', 'yeh', 'lav', 'sox', 'aid', 'cup', 'she', 'kep', 'mux', 'mom', 'eke',
                               'urb', 'web', 'fly', 'mim', 'nim', 'abs', 'gif', 'eve', 'tis', 'tan', 'bel', 'may',
                               'loo', 'jun', 'lye', 'sop', 'tug', 'fer', 'lip', 'man', 'mig', 'lad', 'lam', 'obe',
                               'eau', 'yod', 'mid', 'fay', 'guy', 'rag', 'taj', 'any', 'ope', 'yup', 'lah', 'dad',
                               'gab', 'lev', 'hah', 'heh', 'rug', 'gor', 'ago', 'erg', 'keg', 'shy', 'bam', 'fug',
                               'eat', 'vat', 'ere', 'cwm', 'zed', 'mir', 'ose', 'rig', 'ryu', 'ail', 'udo', 'lax',
                               'pam', 'rue', 'art', 'sol', 'fag', 'elk', 'wis', 'zee', 'cee', 'mag', 'awl', 'tao',
                               'ton', 'het', 'oda', 'sos', 'mam', 'pie', 'tog', 'wan', 'bod', 'zen', 'fem', 'tiz',
                               'tye', 'nun', 'oho', 'cuz', 'pro', 'huh', 'eds', 'tag', 'met', 'rah', 'eco', 'ohm',
                               'roc', 'ken', 'ear', 'hoo', 'ain', 'apo', 'zoa', 'seg', 'bay', 'hoy', 'mum', 'lum',
                               'uta', 'tes', 'fid', 'age', 'fub', 'lay', 'all', 'bus', 'pes', 'beg', 'yay', 'las',
                               'bib', 'bum', 'mae', 'cry', 'mar', 'gan', 'nub', 'piu', 'fiz', 'flu', 'ors', 'jug',
                               'hin', 'lis', 'maw', 'ref', 'dui', 'era', 'psi', 'too', 'fie', 'rye', 'kid', 'gox',
                               'pay', 'sat', 'ewe', 'sho', 'pin', 'pig', 'deb', 'fez', 'yom', 'ted', 'lab', 'tip',
                               'gym', 'shh', 'poh', 'oar', 'meg', 'oba', 'aji', 'and', 'coz', 'peg', 'zag', 'zig',
                               'lar', 'new', 'dah', 'its', 'sun', 'ops', 'did', 'den', 'mho', 'pad', 'rum', 'gag',
                               'sag', 'war', 'sac', 'ree', 'was', 'ska', 'yar', 'dan', 'wos', 'umm', 'urd', 'lud',
                               'pic', 'say', 'dal', 'raj', 'see', 'vau', 'lun', 'wat', 'mix', 'two', 'yow', 'hep',
                               'bag', 'mib', 'pye', 'him', 'bal', 'dee', 'kos', 'pht', 'pug', 'imp', 'gis', 'aft',
                               'cub', 'kae', 'kef', 'oes', 'phi', 'bot', 'aga', 'dog', 'nod', 'one', 'ghi', 'gun',
                               'suk', 'cut', 'emu', 'ave', 'run', 'vex', 'cep', 'tec', 'are', 'ado', 'her', 'oak',
                               'dug', 'wab', 'ooh', 'voe', 'iff', 'jab', 'irk', 'pip', 'pow', 'vin', 'feh', 'don',
                               'put', 'fan', 'owt', 'why', 'jet', 'cob', 'wig', 'tum', 'kis', 'efs', 'rec', 'alt',
                               'ays', 'yew', 'pat', 'ars', 'kif', 'mas', 'nam', 'taw', 'gam', 'rid', 'ten', 'yuk',
                               'far', 'lit', 'cud', 'oaf', 'boa', 'doc', 'sin', 'bub', 'nog', 'leu', 'toy', 'aim',
                               'moa', 'hic', 'zin', 'rep', 'pix', 'tau', 'zax', 'cad', 'ply', 'aha', 'soh', 'cis',
                               'orc', 'fed', 'def', 'ins', 'nap', 'pol', 'ump', 'had', 'din', 'mol', 'fax', 'dip',
                               'kye', 'our', 'peh', 'sit', 'odd', 'for', 'nix', 'fes', 'oat', 'hie', 'cam', 'get',
                               'pom', 'ort', 'air', 'yok', 'sky', 'ram', 'ism', 'lux', 'mot', 'sub', 'att', 'ban',
                               'bas', 'spy', 'sib', 'tat', 'yap', 'jam', 'nan', 'bro', 'hes', 'row', 'gel', 'dey',
                               'zoo', 'fee', 'qis', 'dit', 'ifs', 'god', 'jog', 'ono', 'ate', 'rez', 'gie', 'vum',
                               'ums', 'fil', 'ser', 'per', 'mat', 'hod', 'hun', 'tas', 'wet', 'fou', 'kat', 'ens',
                               'ama', 'luv', 'noh', 'pea', 'sev', 'tom', 'who', 'nag', 'ora', 'dud', 'dig', 'pia',
                               'git', 'fad', 'his', 'sex', 'dis', 'ink', 'hae', 'pal', 'hum', 'rut', 'rya', 'dye',
                               'ana', 'pod', 'tin', 'tup', 'sab', 'out', 'buy', 'wed', 'via', 'yep', 'lib', 'mog',
                               'paw', 'mor', 'axe', 'bow', 'vow', 'but', 'ais', 'pak', 'mus', 'oxo', 'yaw', 'cum',
                               'use', 'nom', 'edh', 'lin', 'wyn', 'jus', 'eek', 'wag', 'eth', 'bet', 'box', 'ess',
                               'fop', 'dot', 'boo', 'ell', 'hew', 'joe', 'nah', 'soc', 'syn', 'fat', 'nor', 'few',
                               'pac', 'ire', 'kab', 'nus', 'rip', 'nee', 'lei', 'woo', 'zzz', 'old', 'ern', 'sty',
                               'hug', 'aah', 'els', 'fro', 'eel', 'spa', 'own', 'xis', 'ick', 'bat', 'inn', 'lie',
                               'ute', 'gul', 'yea', 'qat', 'gig', 'wen', 'sad', 'var', 'wow', 'how', 'led', 'dun',
                               'amp', 'igg', 'pya', 'jay', 'kaf', 'lot', 'hit', 'rex', 'vog', 'mil', 'yen', 'meh',
                               'mug', 'dag', 'nug', 'top', 'moi', 'dab', 'tad', 'wax', 'men', 'kas', 'nil', 'sot',
                               'vie', 'yak', 'tui', 'kit', 'alb', 'thy', 'has', 'bed', 'sus', 'hem', 'yon', 'yas',
                               'bun', 'rob', 'rib', 'yin', 'eta', 'tea', 'fin', 'mun', 'tho', 'myc', 'ret', 'rub',
                               'doe', 'pry', 'pas', 'gip', 'not', 'vim', 'sod', 'elm', 'max', 'hen', 'mud', 'lea',
                               'ohs', 'zip', 'fog', 'off', 'let', 'hey', 'asp', 'die', 'rei', 'mew', 'bos', 'yip',
                               'hon', 'sir', 'oxy', 'cos', 'ems', 'sri', 'tie', 'med', 'ahi', 'hob', 'ecu', 'egg',
                               'cat', 'fey', 'cox', 'ego', 'tit', 'dak', 'soy', 'wap', 'boy', 'cow', 'goa', 'hay',
                               'nit', 'act', 'noo', 'gad', 'gut', 'est', 'ria', 'cay', 'awn', 'brr', 'can', 'tee',
                               'add', 'pec', 'oil', 'vaw', 'con', 'tic', 'das', 'gal', 'doh', 'gen', 'got', 'res',
                               'roe', 'obi', 'dep', 'duh', 'lat', 'aas', 'dam', 'oft', 'urp', 'mel', 'ale', 'yum',
                               'rif', 'kex', 'jar', 'bap', 'ass', 'dim', 'mad', 'mmm', 'pox', 'ley', 'sap', 'cop',
                               'hue', 'ich', 'fir', 'kay', 'low', 'gey', 'arm', 'bar', 'pen', 'ala', 'upo', 'oke',
                               'arf', 'ape', 'sau', 'uns', 'wha', 'bis', 'opa', 'vac', 'oot', 'amu', 'jag', 'cue',
                               'foo', 'suq', 'gas', 'sue', 'fah', 'ait', 'pap', 'ash', 'cog', 'cod', 'jig', 'mob',
                               'now', 'six', 'rho', 'vid', 'won', 'hao', 'cab', 'sic', 'jow', 'ran', 'ace', 'rad',
                               'fib', 'lap', 'fas', 'hoe', 'hap', 'eng', 'kob', 'fix', 'fur'}

if __name__ == '__main__':
    pass
